<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="two_DoF_leg" params="
    prefix 
    parent_link 
    x_offset 
    y_offset
    z_offset
    radius
    upper_length
    lower_length 
    first_joint_min_lim
    first_joint_max_lim
    second_joint_min_lim
    second_joint_max_lim">
          
        <link name="${prefix}_upper_leg_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${upper_length}"/>
                </geometry>
                <origin xyz="0 0 ${-upper_length/2.0}" rpy="0 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${upper_length}"/>
                </geometry>
                <origin xyz="0 0 ${-upper_length/2.0}" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${upper_length}"
                                     xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        </link>

        <link name="${prefix}_lower_leg_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${lower_length}"/>
                </geometry>
                <origin xyz="0 0 ${-lower_length/2.0}" rpy="0 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${lower_length}"/>
                </geometry>
                <origin xyz="0 0 ${-lower_length/2.0}" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${lower_length}"
                                     xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        </link>

        <link name = "${prefix}_foot_link">
            <visual>
                <geometry>
                    <sphere radius = "${radius}"/>
                    <origin xyz = "0 0 0" rpy = "0 0 0"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius = "${radius}"/>
                    <origin xyz = "0 0 0" rpy = "0 0 0"/>
                </geometry>
            </collision>
            <xacro:sphere_inertia m="0.5" r="${radius}"
                                xyz = "0 0 0" rpy = "0 0 0"/>
        </link>

        <joint name="${prefix}_upper_leg_joint" type="continuous">
            <parent link="${parent_link}"/>
            <child link="${prefix}_upper_leg_link"/>
            <origin xyz = "${x_offset} ${y_offset} ${z_offset}" rpy = "0 0 0"/>
            <axis xyz = "0 1 0"/>
        </joint>

        <joint name="${prefix}_lower_leg_joint" type="continuous">
            <parent link="${prefix}_upper_leg_link"/>
            <child link="${prefix}_lower_leg_link"/>
            <origin xyz = "0 0 ${-upper_length}" rpy = "0 0 0"/>
            <axis xyz = "0 1 0"/>
        </joint>

        <joint name="${prefix}_foot_joint" type="fixed">
            <parent link = "${prefix}_lower_leg_link"/>
            <child link = "${prefix}_foot_link"/>
            <origin xyz = "0 0 ${-lower_length}" rpy = "0 0 0"/>
        </joint>
    </xacro:macro>

</robot>